version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    tty: true
    restart: always
    working_dir: /home/node/app
    networks: 
      - node_app_network
  nginx:
    container_name: nginx_app
    image: nginx:1.19.2-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/nginx/html
    depends_on:
      - app
    networks: 
      - node_app_network

#Docker Networks
networks: 
  node_app_network:
    driver: bridge